#!/bin/python3

VERSION = '1.0'

help = """
 annotation-ctrl is a single button GUI for annotation-mgr that toggles displaying or not 
                 displaying PDF annotations that have been saved by annotation-mgr.

                 The command 'annotation-ctrl' starts annotation-mgr (if not running) and also 
                 displays a single button GUI for starting and stopping the annotation-mgr process.

                 See: annotation-mgr --help  

 Usage:          Typically annotation-ctrl would be started automatically after KDE starts. This
                 can be achieved using ~/.config/autostart-scripts. The file,

                      start-annotation-ctrl.sh 

                 is an autostart script. See the comments in that file for how to install it.    

 Options:        -h, --help      will print this documentation then exit.     

                 -v, --version   will print the version number then exit. 

                 -p, --position  pixel position of the button window: +x+y, -x+y, +x-y, -x-y. 
                                 +/- measures from left/right (for x) or top/bottom (for y). 
                                 E.g., --position '-0+0' is at top right corner of the screen. 

                 -e, --exclude   passed to annotation_mgr. See: annotation-mgr --help 

                 -d, --debug     passed to annotation_mgr. See: annotation-mgr --help  
"""

from tkinter import *
from tkinter import ttk
import subprocess
import re
from controls_file import * 

# -------------------------------------------------------------------------------------------------

home = os.path.expanduser('~') + '/'
dotdir = home + '.annotation-manager/'

controls_file_location(dotdir + 'controls.dat')
controls_read()
controls_set('status', 'unknown')
controls_write()

# -------------------------------------------------------------------------------------------------
# Options.

import sys
import getopt

try:
    (opts, args) = getopt.getopt(sys.argv[1:], "vhp:de:", ["version", "help", "position=", "debug", "exclude="])
except:
    print("annotation-ctrl: Unknown option. Quitting.")
    quit()

opts_dict = dict(opts)

if ('-v' in opts_dict) or ('--version' in opts_dict):
    print(VERSION)
    quit()
    
if ('-h' in opts_dict) or ('--help' in opts_dict):
    print(help)
    quit()

options = ''    
if ('-d' in opts_dict) or ('--debug' in opts_dict):
    options = ' -d'
    debug = True
else:
    debug = False
    
if ('-p' in opts_dict):
    initial_pos = opts_dict['-p']
    controls_set('position', initial_pos)
    controls_write()
elif ('--position' in opts_dict):
    initial_pos = opts_dict['--position']
    controls_set('position', initial_pos)
    controls_write()
else:
    initial_pos = controls_get('position')

if debug: print('annotation-ctrl: initial_pos =', initial_pos)
    
if ('-e' in opts_dict):
    options = options + ' -e ' + opts_dict['-e']    
elif ('--exclude' in opts_dict):
    options = options + ' -e ' + opts_dict['--exclude']

# -------------------------------------------------------------------------------------------------
# Path to scripts.

scripts = os.path.dirname(os.path.realpath(__file__))
if debug: print('annotation-ctrl: scripts =', scripts)

# -------------------------------------------------------------------------------------------------

def start_annotation_mgr():
    controls_read()
    if not controls_get('status') == 'running':
        controls_set('status', 'running')
        controls_write()
        subprocess.run(scripts + '/annotation-mgr' + options + ' &', shell=True)
        lab['text'] = "Annotation manager is running."
        b0['text'] = 'Stop'
        b0['command'] = stop_annotation_mgr 

def stop_annotation_mgr():
    controls_read()
    if not controls_get('status') == 'stopping':    
        controls_set('status', 'stopping')
        controls_write()
        lab['text'] = "Annotation manager is not running."
        b0['text'] = 'Start'
        b0['command'] = start_annotation_mgr

def save_position(event):
    pos = position() 
    x = root.winfo_rootx()    #  +6 offset -- probably window theme specific, not used.
    y = root.winfo_rooty()    # +31 offset -- probably window theme specific, not used.   
    xypos = '+' + str(x) + '+' + str(y)    
    if debug: print('save_position(): event =', event)
    if debug: print('save_position(): pos =', pos)
    if debug: print('save_position(): xypos =', xypos)
    controls_set('position', pos)
    controls_write()

# -------------------------------------------------------------------------------------------------
# Position from geometry.
#
# If the window is dragged beyond the left or the top of the screen then root.geometry()
# will return strings with minus signs like, '279x79+-48+-37', '279x79+1341+-44'.
# Replace +- values by +0 and put the window back inside the screen.
#
# Similarly, if the window is dragged beyond the right or the bottom of the screen then root.geometry()
# can return strings with signs like, '279x79--48--37', '279x79+1341--44'.
# Replace -- values by -0 and put the window back inside the screen.
#
# The +/- signs in geometry specify the direction and origin of coords. Once set, geometry() returns
# the same coords (i.e., uses the same signs).

def position():
    g = root.geometry()
    if debug: print('position(): g =', g)
    g0 = re.sub('\+-[0-9]*','+0', g)
    g1 = re.sub('--[0-9]*','-0', g0)
    [xstr, ystr] = re.findall('[+-][0-9]*', g1)
    pos = xstr + ystr
    if ('+-' in g) or ('--' in g):
        root.geometry(pos)
    return pos
    
# -------------------------------------------------------------------------------------------------
# Adapted from: http://tkdocs.com/tutorial/firstexample.html
# https://tkdocs.com/shipman/

root = Tk()

width  = root.winfo_screenwidth()  
height = root.winfo_screenheight() 
if debug: print('Screen size =', width, height)

if not initial_pos == None:
    if debug: print('Setting geometry: initial_pos =', initial_pos)
    root.geometry(initial_pos)
    # root.update()

root.title("annotation-ctrl")

root.bind("<Configure>", save_position)

frame = ttk.Frame(root)

frame['padding'] = (3, 5, 3, 5)           # L,T,R,B
frame.grid()

lab = ttk.Label(frame, text="", width=29, anchor='center')
lab.grid(row=1)

b0 = ttk.Button(frame)
b0.grid(row=2)

for child in frame.winfo_children(): 
    child.grid_configure(padx=5, pady=5)

start_annotation_mgr()

root.mainloop()


